name: Monitor SEIA

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  # cada 10 minutos

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install beautifulsoup4 pandas requests

      - name: Run script
        run: python alerta_expediente_cnx.py
        env:
          OUTLOOK_USER: ${{ secrets.OUTLOOK_USER }}
          OUTLOOK_PASSWORD: ${{ secrets.OUTLOOK_PASSWORD }}
          MAIL_DESTINO: ${{ secrets.MAIL_DESTINO }}

      - name: Set GitHub remote with token
        run: git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

      - name: Commit updated CSV to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add test_reclamos.csv
          git commit -m "Actualizar base de datos de expediente" || echo "Sin cambios que commitear"
          git push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
